[package]
name = "Cr3_image_transform"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.7.0"
image = "0.24.1"
rawloader = "0.37.1"
crossbeam = "0.8.1"
jpeg-decoder = "0.1.22"
